version: 1.0.{build}

before_build:
  - dotnet restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: TmLox.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"nunit-console.exe" -targetargs:".\TmLox.Interpreter.Tests\bin\Debug\TmLox.Interpreter.Tests.dll -noshadow" -filter:"+[*]*" -output:coverage.xml

after_test:
  - codecov -f "coverage.xml"