version: "{build}"
image: Visual Studio 2019

before_build:
  - dotnet restore
  - choco install codecov
  - choco install opencover.portable

build:
  project: TmLox.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:coverage.xml -oldstyle

after_test:
  - codecov -f "coverage.xml"