version: 1.0.{build}

before_build:
  - dotnet restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: TmLox.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"dotnet" -output:".\coverage.xml"

after_test:
  - codecov -f "coverage.xml"