version: 1.0.{build}
image: Visual Studio 2019

before_build:
  - dotnet restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: TmLox.sln
  verbosity: minimal

test_script:
  - OpenCover.Console.exe -register:user -target:"nunit-console.exe" -targetargs:test -filter:"+[*]*" -output:coverage.xml

after_test:
  - codecov -f "coverage.xml"